Repository bulwark-security/bulwark, pull requests merged in 2023-07, with the labels that each got.

#67 Capture and log stdio from plugins
  crates/ext-processor/src/service.rs
  crates/wasm-host/src/plugin.rs
Labels: kind/usability, kind/enhancement

#68 Context wrappers
  crates/wasm-host/src/plugin.rs
Labels: size/medium, kind/cleanup

#72 Implement handling for request and response bodies
  crates/ext-processor/examples/envoy.yaml
  crates/ext-processor/src/errors.rs
  crates/ext-processor/src/service.rs
  crates/wasm-host/src/plugin.rs
  crates/wasm-sdk-macros/src/lib.rs
  crates/wasm-sdk/src/from.rs
  crates/wasm-sdk/src/host_api.rs
  grep
  wit/plugin.wit
Labels: size/xx-large, kind/bug, kind/cleanup, kind/enhancement, area/plugin-api

#78 Added shorthand commands for log_level and log_format
  src/main.rs
Labels: triage/accepted, size/x-small, kind/bug

#80 Simplify plugin builds
  .gitignore
  Cargo.lock
  Cargo.toml
  adapter/.gitkeep
  build.rs
  src/build.rs
  src/errors.rs
  src/main.rs
Labels: kind/usability

#86 Update wasmtime
  .gitignore
  Cargo.lock
  adapter/wasi_snapshot_preview1.reactor.wasm
  build.rs
  crates/wasm-host/.gitignore
  crates/wasm-host/Cargo.toml
  crates/wasm-host/build.rs
  crates/wasm-host/tests/wasi_snapshot_preview1.reactor.wasm
Labels: size/small, kind/cleanup, dependencies

#85 This TODO has already been resolved
  src/main.rs
Labels: size/x-small, kind/cleanup

#96 Flush IO after every handler runs
  crates/wasm-sdk-macros/src/lib.rs
Labels: size/x-small, kind/bug

#92 Automatically generated metrics
  Cargo.lock
  Cargo.toml
  crates/config/src/config.rs
  crates/config/src/toml.rs
  crates/config/tests/main.toml
  crates/ext-processor/Cargo.toml
  crates/ext-processor/src/service.rs
  crates/wasm-host/Cargo.toml
  crates/wasm-host/src/plugin.rs
  src/admin.rs
  src/errors.rs
  src/main.rs
Labels: size/x-large, kind/enhancement
