Repository bulwark-security/bulwark, pull requests merged in 2023-08, with the labels that each got.

#97 Fix feedback handler's stdio not being captured
  crates/ext-processor/src/service.rs
Labels: size/medium, kind/bug

#98 Current directory was missing from the sub process
  src/build.rs
  src/main.rs
Labels: kind/bug, kind/usability

#99 This was probably a terminal typo that got accidentally committed
  grep
Labels: size/x-small, kind/bug, kind/cleanup

#100 Hide undocumented items
  crates/wasm-host/src/plugin.rs
  crates/wasm-sdk-macros/src/lib.rs
  crates/wasm-sdk/src/lib.rs
Labels: size/small, kind/cleanup, kind/docs, kind/usability

#101 Macro tests weren't running
  .github/workflows/rust.yml
Labels: size/x-small, kind/bug

#102 Improve documentation for Decision structures
  crates/decision/src/decision.rs
Labels: size/small, kind/docs, kind/usability

#103 Improve docs for the bulwark_plugin attribute macro
  crates/wasm-sdk-macros/src/lib.rs
  crates/wasm-sdk/src/lib.rs
Labels: size/medium, kind/docs, area/plugin-api

#104 cli: print help when no subcommand is provided
  src/errors.rs
  src/main.rs
Labels: size/x-small, kind/bug, kind/cleanup

#105 Bumping version to 0.3.0
  Cargo.lock
  Cargo.toml
  crates/config/Cargo.toml
  crates/decision/Cargo.toml
  crates/ext-processor/Cargo.toml
  crates/wasm-host/Cargo.toml
  crates/wasm-sdk-macros/Cargo.toml
  crates/wasm-sdk/Cargo.toml
  crates/wasm-sdk/examples/blank-slate/Cargo.toml
  crates/wasm-sdk/examples/evil-bit/Cargo.toml
Labels: size/small

#107 Somehow we still have too many keywords 3 releases in
  Cargo.toml
Labels: kind/cleanup

#115 Add semaphores to limit concurrency
  crates/config/src/config.rs
  crates/config/src/toml.rs
  crates/ext-processor/src/service.rs
Labels: size/large, kind/usability, kind/enhancement

#116 Use a shared HTTP client
  Cargo.lock
  crates/ext-processor/Cargo.toml
  crates/ext-processor/src/service.rs
  crates/wasm-host/src/plugin.rs
Labels: size/medium, kind/bug, kind/cleanup

#117 Refactor processor functions to use self reference
  crates/ext-processor/src/service.rs
Labels: size/large, kind/cleanup

#119 Conflict measurement
  crates/decision/src/decision.rs
  crates/ext-processor/src/service.rs
  src/main.rs
Labels: size/large, kind/usability, kind/enhancement

#125 add outcome to header
  crates/ext-processor/src/headers.rs
  crates/ext-processor/src/service.rs
Labels: size/medium, kind/usability, kind/enhancement

#127 Reexport the json macro as a value macro
  crates/wasm-sdk/src/host_api.rs
Labels: size/x-small, kind/usability, area/plugin-api

#128 Allow arguments to be passed through to cargo
  src/build.rs
  src/main.rs
Labels: kind/usability, kind/enhancement

#131 pin third party actions to full SHAs
  .github/workflows/rust.yml
Labels: size/x-small
